name: "[CD] Continuous Delivery v3"

on:
  push:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_V3 }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_V3 }}

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: "Debug"
        run: |
          ls -la
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Deploy"
        run: "npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}"
